name: Build Main

on:
  push:
    branches: [ main, ghactions ]

env:
  IMAGE_NAME: preflight-trigger

permissions: {}

jobs:
  build-main:
    name: Build and push main snapshot images
    permissions:
      contents: read
    strategy: 
      matrix:
        architecture: [amd64]
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
        # Get tags and all history in order to find latest tag in later step
        fetch-depth: 0
        fetch-tags: true

    - name: Set Env Tags
      run: echo "RELEASE_TAG=$(git describe --abbrev=0 --tags)" >> "${GITHUB_ENV}"

    - name: set short sha
      run: echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        # TODO: If we end up releasing for other architectures we'll need the below
        # tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        tags: ${{ env.SHA_SHORT }}
        archs: ${{ matrix.architecture }}
        build-args: |
          quay_expiration=1w
          release_tag=${{ env.RELEASE_TAG }}+${{ github.sha }}
          ARCH=${{ matrix.architecture }}
        dockerfiles: |
          ./Dockerfile

    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
      with:
        image: ${{ env.IMAGE_NAME }}
        # TODO: If we end up releasing for other architectures we'll need the below
        # tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ matrix.architecture }}
        tags: ${{ env.SHA_SHORT }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
    
    outputs:
      imageName: ${{ env.IMAGE_NAME }}
      imageVersion: ${{ env.SHA_SHORT }}

  build-coverage:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Install system deps
      run: 'sudo apt update && sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev'

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        cache: false
        go-version-file: go.mod

    - name: Tidy
      run: make tidy

    - name: Vet
      run: make vet

    - name: Format
      run: make fmt

    - name: Test
      run: make cover
